###
http://petsapp-api.herokuapp.com/pets/api/v1/post/

###
http://petsapp-api.herokuapp.com/pets/api/v1/search_by_category/?category=dog


###
http://petsapp-api.herokuapp.com/pets/api/v1/get_municipality?district=1


###
http://petsapp-api.herokuapp.com/pets/api/v1/search_animal/?pet_name=dog


###
http://petsapp-api.herokuapp.com/pets/api/v1/filter_location/?district=1&municiapality=1&location=syangja arjunchaupari

###
http://petsapp-api.herokuapp.com/pets/api/v1/all_district/

###
http://petsapp-api.herokuapp.com/api/login/ 


###
http://petsapp-api.herokuapp.com/api/register/ 


###
http://petsapp-api.herokuapp.com/api/login/refresh 