version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=pets_app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=pets_app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      - db


# version: '3.9'
# services:
#   web:
#     build: .
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./:/usr/src/pets_app_api/
#     ports:
#       - 8000:8000
#     env_file:
#       - ./.env
#     depends_on:
#       - db
#   db:
#     image: postgres:13.0-alpine
#     volumes:
#       - postgres_data_petsapp:/var/lib/postgresql/data/
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=admin
#       - POSTGRES_DB=pets_app
  
#   #redis:
#     #image: redis:alpine
#   #celery:
#     #restart: always
#     #build:
#       #context: .
#     #command: celery -A config_pannel worker -l info
#     #volumes:
#      # - ./:/usr/src/asset-management-tool/
#     #env_file:
#      # - ./.env.dev
#     #depends_on:
#      # - db
#       #- redis
#       #- web
# volumes:
#   postgres_data_petsapp:

