# Generated by Django 4.0.2 on 2022-03-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
