# Generated by Django 4.0.2 on 2022-03-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_userprofile_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='district',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='municipality',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
