# Generated by Django 4.0.2 on 2022-03-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0007_remove_userprofile_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
