# Generated by Django 4.0.2 on 2022-03-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0009_remove_userprofile_post_userprofile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
