# Generated by Django 4.0.2 on 2022-04-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_rename_user_id_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petdetailpost',
            name='user_contact',
            field=models.CharField(max_length=20),
        ),
    ]
