# Generated by Django 4.0.2 on 2022-04-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_alter_petdetailpost_user_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='contact_no',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='choices',
            field=models.ManyToManyField(to='pets.AnimalCategory'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
