# Generated by Django 4.0.2 on 2022-04-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0015_alter_petdetailpost_breed_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
