# Generated by Django 4.0.2 on 2022-04-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0016_alter_animalcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='breed',
            field=models.CharField(max_length=40),
        ),
    ]
