# Generated by Django 4.0.2 on 2022-03-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_user'),
        ('todo', '0002_todo_user'),
    ]

    operations = [
    ]
